site_name: Disclosure documentation

pages:
- Introduction:
    - 'Quickstart': 'index.md'
- Basic usage:
    - 'Simple assignment': 'basic/simple.md'
    - 'Advance declaration': 'basic/advance-declaration.md'
- Advanced topics:
    - 'Using marker interfaces': 'advanced/marker-interfaces.md'
    - '(Un)sharing dependencies': 'advanced/sharing.md'
- API reference:
    - 'Container': 'api/container.md'
    - 'Injector': 'api/injector.md'

