site_name: Disclosure documentation

pages:

- [index.md, Introduction, Quickstart]

- [basic/simple.md, Basic usage, Simple assignment]
- [basic/advance-declaration.md, Basic usage, Advance declaration]

- [advanced/marker-interfaces.md, Advanced topics, Using marker interfaces]

theme: readthedocs
